apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: irnlln4bb-go 
  janus-idp.io/tekton: irnlln4bb-go
  backstage.io/kubernetes-id: irnlln4bb-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: irnlln4bb-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml