apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: irnlln4bb-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: irnlln4bb-go 
  name: irnlln4bb-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: irnlln4bb-go 
